### ISSUE TITLE
The cluster indicator is not working but time input is working

### ISSUE THREAD

**Issue by Jewelleryliu** [TeksuSiK/e46-cluster-simhub#1]

**Comment by Jewelleryliu** [comment]
Hello, my instrument indicator light does not work, but the time is correct, and the query for various kbus codes still does not take effect.

**Comment by TeksuSiK** [comment]
Hello, I have tested everything on my setup and it seems to works. If you have tried adding other K-Bus messages make sure there are valid, because sending invalid messages will interrupt communication on bus

**Comment by Jewelleryliu** [comment]
Customized serial devices cannot automatically connect, you need to repeatedly click on update measea edit JS before receiving feedback。

**Comment by TeksuSiK** [comment]
Looks like a problem with SimHub. The only thing I can tell you is to check that the payload being sent matches the specifications in the serial receive code. The number of elements in the message must match and the message must end with ";\n"

**Comment by Jewelleryliu** [comment]
Hello, the chip I am using is MCP2021A-500E/SN, and pin 3 VRGE is not connected. Previously, only time could be set without a light tube, but now k-bus is completely unusable. Please forgive my poor English proficiency. Thank you for your code and response.

**Comment by TeksuSiK** [comment]
VREG is not mandatory to connect. It only outputs a stabilized 5V voltage, which can be used, for example, to connect a microcontroller. Make sure you apply 12V to the VBB connector as this is required for the chip to turn on the transmitter. Also make sure that CS and TXE are high, the TX/RX outputs are connected to their corresponding Serial connectors on the Arduino (in the case of this code it is Serial2) and that the entire circuit has a common ground. Otherwise, if these things not working maybe your chip is damaged.

**Comment by Jewelleryliu** [comment]
It's all designed according to your circuit diagram. Is it possible that there is something wrong with my instrument? My chip uses a multmeter to measure the pin voltage normally.And I bought a lot of such chips.

https://github.com/TeksuSiK/e46-cluster-simhub/assets/165434570/55cf2bce-3d77-4101-a712-4fed9dd6380c

 My meter is from 2003, bus:13H, can:07H

**Comment by Jewelleryliu** [comment]
![image](https://github.com/TeksuSiK/e46-cluster-simhub/assets/165434570/aa60d79d-862b-4980-8231-dcd5c9a31620)
Time is right，no indicator

**Comment by TeksuSiK** [comment]
Can you check whether, if you send a different time afterwards, whether it will be set on the counter, or whether, if you change the time on the counter manually using the knob, whether it will change in a moment to the one that SimHub should send. As I understand it, other lights such as high beams or fog lights do not work either?

**Comment by Jewelleryliu** [comment]
The time will not change immediately. You can restart the instrument and the time can be updated. However, the indicator light does not work, and the contact may be bad if it has not been updated before. But now after restarting the instrument, the time can be updated, and I have never used the knob. Is my instrument broken?

**Comment by TeksuSiK** [comment]
Can you send me the exact custom protocol you use in SimHub? And if I understand correctly, you are currently using an unmodified version of the code?

**Comment by Jewelleryliu** [comment]
The code is used according to what you provide. It seems that the time is not because the connection is unstable, the handbrake light is always on, the can protocol is normal, the k bus cannot be used, the indicator light does not take effect, and the time can be set occasionally, but the time update must be restarted. The code is used according to what you provide. It seems that the time is not because the connection is unstable, the handbrake light is always on, the can protocol is normal, the k bus cannot be used, the indicator light does not take effect, and the time can be set occasionally, but the time update must be restarted.
![image](https://github.com/TeksuSiK/e46-cluster-simhub/assets/165434570/df443c89-0463-448a-b7b1-a47e3319e0e2)

![image](https://github.com/TeksuSiK/e46-cluster-simhub/assets/165434570/1578b0af-b082-48db-b29c-a3ad3a2c0684)
![image](https://github.com/TeksuSiK/e46-cluster-simhub/assets/165434570/cd4944bb-731e-49bd-bb3e-2686312d6030)

**Comment by Jewelleryliu** [comment]
Uploading 7a299b1513ca7efc14889a0b84e84c.mp4…

**Comment by Jewelleryliu** [comment]
https://github.com/TeksuSiK/e46-cluster-simhub/assets/165434570/71332f72-8593-481c-9e16-877ef9c0aed4

**Comment by TeksuSiK** [comment]
Can you pull the latest version of code and check if the problem persists? Unfortunately, I don't have access to my setup for now, so I can't check it. Additionally, looking at the photo you sent, the order of the fields in SimHub does not match. According to the photo, the rear fog lights are fixed set to 0, but according to the returned value, in the place where the value for these lights should be located, you have it set to 1. If the order of information sent by SimHub to Arduino does not match, the data will not be processed correctly.

**Comment by Jewelleryliu** [comment]
The code is provided by you, including the Simhub protocol. I use the serial debugging tool to set the switch amount to 1. There should be a light to turn on, but all the lights related to kbus are not on (except for the handbrake light is always on), and the time can not be set every time. If I buy another e46 meter, are there any restrictions? For example, the year of production and the nameplate information are different. Can you make a relevant video? Maybe this is a special case for me.
![image](https://github.com/TeksuSiK/e46-cluster-simhub/assets/165434570/0fa882ee-a8f5-47d1-a48f-02b8f009ea3f)
![image](https://github.com/TeksuSiK/e46-cluster-simhub/assets/165434570/6b8ad885-fc78-4ddd-8e0b-fe55697c6580)

**Comment by TeksuSiK** [comment]
Have you tested the latest update I released? It may be the solution to your problem. Let me know.

**Comment by Jewelleryliu** [comment]
Thank you. I will test it on the evening of April 7th, China time.

**Comment by Jewelleryliu** [comment]
Sorry, it still doesn't work. Did you change frameIndicators [9] to frameIndicators [8]? When my instrument time was working, I tried to change the code of the indicator light, referring to the code of LCM III. I have also changed the serial port before. None of them work. The handbrake indicator light is constantly on. But during my instrument self check, all indicator lights can light up. What if I buy another instrument panel? Is it possible to use an E46 instrument produced in 1998? Thank you!

**Comment by Jewelleryliu** [comment]
![image](https://github.com/TeksuSiK/e46-cluster-simhub/assets/165434570/5a3fb076-38fa-4196-a11a-9f6947728ec4)
I have tried all the bytes, but none of them worked. I am sure there is no problem with the connection, and I have customized the circuit board. It can conduct with a multimeter.

**Comment by TeksuSiK** [comment]
I created a new [branch](https://github.com/TeksuSiK/e46-cluster-simhub/tree/lcm_iv) where I changed the message to match LCM_IV version. It is possible that your counter does not support the previous version of the frame due to its MY. Unfortunately, I don't remember what year my cluster was and I have no way to check it now. If that doesn't work, I have one more idea up my sleeve.

**Comment by TeksuSiK** [comment]
However, when it comes to the handbrake indicator, it is controlled by pulling up to the ground. From what I've seen, your odometer doesn't beep while you're driving, so it doesn't mean it's pulled. It may be an error symbol of an unconnected BRFN or BBV+ sensor. From what I remember, they had to be pulled up to the ground. When you turn on the meter and the hands are calibrating, do you hear any beeping?

**Comment by Jewelleryliu** [comment]
Pull the handbrake while driving and the beep will sound the alarm. The beeping sound should be normal.

**Comment by Jewelleryliu** [comment]
![image](https://github.com/TeksuSiK/e46-cluster-simhub/assets/165434570/408b9e39-d1ad-4245-8279-492997595332)
![image](https://github.com/TeksuSiK/e46-cluster-simhub/assets/165434570/be3fc368-c8c6-40b8-944e-c3bd46e0d279)

**Comment by Jewelleryliu** [comment]
What does MY mean?

**Comment by TeksuSiK** [comment]
What I meant was that if there is no beeping sound while driving and the handbrake light is on all the time, it is a problem with one of the additional sensors. Try to pull pins 20 and 24 on the cluster to ground. What about the change from the LCM_IV branch I made. Have you tested it?

**Comment by Jewelleryliu** [comment]
I have tested it, and it didn't work. Is my instrument bad? Pins 20 and 24 connected to ground. Handbrake indicator light receive kbus control。Pins 4,5,6 connected 12v

**Comment by Jewelleryliu** [comment]
![image](https://github.com/TeksuSiK/e46-cluster-simhub/assets/165434570/24ae56ae-e86d-4fd6-8b21-581a99a4ab93)
Can bus is ok,Kbus is bad,,,

**Comment by TeksuSiK** [comment]
https://github.com/TeksuSiK/e46-cluster-simhub/archive/refs/heads/lcm_iv.zip

Try downloading this version of code. I temporarily removed the OBC Input frame and added manual checksum calculation and sending the frame to the serial port instead of using the library. Make sure your MCP2021 chip is connected to the Serial2 port of the Arduino.

**Comment by Jewelleryliu** [comment]
When I use the serial debugging tool to assign values, every time the instrument is powered on again, the time can be updated, but the indicator light still doesn't work. Time cannot be updated without restarting the instrument!

**Comment by TeksuSiK** [comment]
[In the version I sent above](https://github.com/TeksuSiK/e46-cluster-simhub/archive/refs/heads/lcm_iv.zip), I turned off the time setting and left only sending indicators, and also changed the way of sending frames. Have you tested this version?

**Comment by Jewelleryliu** [comment]
![image](https://github.com/TeksuSiK/e46-cluster-simhub/assets/165434570/b0b26441-edbf-4eb1-a544-8d35887920fd)
Sorry, what does this mean? I have only been studying for less than a month.

**Comment by TeksuSiK** [comment]
Unfortunately, I don't understand Chinese, but I guess you need to open this project as a PlatformIO project, because it probably doesn't find external library files.

**Comment by Jewelleryliu** [comment]
I can recompile and upload the software by restarting it, but the indicator light still doesn't work. Is it related to my microcontroller being fake?

**Comment by TeksuSiK** [comment]
Then I'm not sure what the problem is. I also have an Arduino clone, although from what I remember mine is detected under a different name. Maybe this is some clue. Also my cluster is from a different year and is made by Motometer, not by Bosch like yours. However, it seems to me that the only difference is the way the backlight is turned on. But if you had access to a Motometer cluster (Probably these are the ones made before 2003), it's worth checking. Tomorrow I will have access to my setup and I will be able to check for myself whether this code works. But as far as I remember, I tested everything and it worked without any problems.

**Comment by Jewelleryliu** [comment]
Thank you. Does your code still apply to other models of BMW meters? I try my best to try again. In China, I can only buy the Chinese version of e46 meters, all of which are produced by Bosch, 2003-2004. I saw an e46 instrument produced by Bosch in 2001 on the second-hand platform in China. I don't know if it will work. I won't give up. Thank you again!

**Comment by Jewelleryliu** [comment]
Is this okay?
![IMG_2257](https://github.com/TeksuSiK/e46-cluster-simhub/assets/165434570/99263586-2970-48ce-97f6-33dcad8bf064)
![IMG_2256](https://github.com/TeksuSiK/e46-cluster-simhub/assets/165434570/96bdb1e6-2d20-475c-b127-ec0c942019e4)
![IMG_2255](https://github.com/TeksuSiK/e46-cluster-simhub/assets/165434570/00dbb1f4-9f19-46ac-b56e-fea1973b4e5f)

**Comment by Jewelleryliu** [comment]
![IMG_2255](https://github.com/TeksuSiK/e46-cluster-simhub/assets/165434570/6ae1f23a-249f-416c-8cf7-8c7728ff51fd)
![IMG_2257](https://github.com/TeksuSiK/e46-cluster-simhub/assets/165434570/e5f0fada-8784-479f-a305-65fc6873d376)

**Comment by Jewelleryliu** [comment]
Uploading ff7302f01411c671a610335665f1c2.mov…

I bought a motomter BMW E46 instrument. Its shell is marked with 1998. All functions can be used, and the normal backlight of the handbrake light is also on. At the beginning. Turn signals, high beams and fog lights were in my debugging and restart of the instrument. They actually worked, but they couldn't be used later, and the time can be displayed normally every time they started. It doesn't work even if I change to mcp2021.

**Comment by Jewelleryliu** [comment]
I bought a motomter BMW E46 instrument. Its shell is marked with 1998. All functions can be used, and the normal backlight of the handbrake light is also on. At the beginning. Turn signals, high beams and fog lights were in my debugging and restart of the instrument. They actually worked, but they couldn't be used later, and the time can be displayed normally every time they started. It doesn't work even if I change to mcp2021.

https://github.com/TeksuSiK/e46-cluster-simhub/assets/165434570/719b393d-d8d5-453e-a3ed-0eb6d339ca68
